FROM ubuntu:18.04

ARG SRC_DIR
ARG APP_PORT

#Copy app package to docker image

RUN echo $PWD
WORKDIR /opt/cs50vn/virustracker
COPY ${SRC_DIR} .
RUN ls -l

EXPOSE ${APP_PORT}

ENTRYPOINT ["./virustracker-crawler-worker"]