name: CI

on:
  push:
    branches:
      - feature/v1

jobs:
  build:
    runs-on: ubuntu-latest
    container: 7perl/build-packs:golang-v1.0.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Dev stage
      env:
        OSS_TEST_CONFIG_URL: ${{ secrets.OSS_TEST_CONFIG_URL }}
        OSS_TEST_DATABASE_URL: ${{ secrets.OSS_TEST_DATABASE_URL }}
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
        OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
        DEV_SERVER_URL: ${{ secrets.DEV_SERVER_URL }}
        DEV_SERVER_USER: ${{ secrets.DEV_SERVER_USER }}
        DEV_SERVER_KEY: ${{ secrets.DEV_SERVER_KEY }}
        OSS_TEST_APP_URL: ${{ secrets.OSS_TEST_APP_URL }}
      run: | 
        ./.ci/scripts/ci-dev.sh $PWD